#!/bin/bash -ev

# TODO: Sort out .pbuilderrc mess on basecamp
# TODO: Gpg Signing (dpkg-sig)
# TODO: Auto determine "sarge" vs "breezy" for TGT below (from /etc/debian_version ?)

VER="0.3.1dev"     # TODO: Should lify this from .tar.gz name

GUESS_DISTRIBUTION=`grep '^DISTRIBUTION=' /etc/pbuilderrc | tail -1`
eval ${GUESS_DISTRIBUTION}
if [[ "${DISTRIBUTION}" == "" ]] ; 
    then echo "Could't guess distribution from /etc/pbuilderrc" ; exit ; 
fi

echo "Assuming distribution is \"${DISTRIBUTION}\""

REV="1${DISTRIBUTION}1"

if [ ! -s "fracplanet-${VER}.tar.gz" ] ; then
    echo "Can't find fracplanet-${VER}.tar.gz"
    exit
fi

rm -r -f pkg
mkdir pkg
cd pkg

cp ../fracplanet-$VER.tar.gz fracplanet_$VER.orig.tar.gz
tar xvfz fracplanet_$VER.orig.tar.gz
mv fracplanet fracplanet-$VER
cd fracplanet-$VER
mv CHANGES changelog          # As per policy manual
sed -i "s/${VER}/${VER}-${REV}/g" VERSION

mkdir debian
echo "fracplanet (${VER}-${REV}) ${DISTRIBUTION}; urgency=low" > debian/changelog
echo >> debian/changelog
echo "  * Package created by fracplanet's mkdeb script." >> debian/changelog
echo >> debian/changelog
DATE=`822-date`
echo " -- $USER <$EMAIL>  $DATE" >> debian/changelog

# Presumably a dch -i here would increment revision

cat << EOF > debian/packages
Source: fracplanet
Section: graphics
Priority: extra
Maintainer: Tim Day <timday@bottlenose.demon.co.uk>
Standards-Version: 3.6.1
Upstream-Source: <URL:http://sourceforge.net/projects/fracplanet/index.htm>
Home-Page: <URL:http://www.bottlenose.demon.co.uk/share/fracplanet>
Description: Fractal terrain generator
Copyright: GPL
 Copyright 2006 Tim Day
Build-Depends: qt3-dev-tools,libqt3-mt-dev,xsltproc,libboost-dev
Build: sh
 export QTDIR=/usr/share/qt3
 # Note: yada install deals with DEB_BUILD_OPTIONS 'nostrip'
 if [ "${DEB_BUILD_OPTIONS#*noopt}" != "$DEB_BUILD_OPTIONS" ]; then
   ./configure "CONFIG -= release" "CONFIG += debug"
 else
   ./configure # No noticeable advantage in overriding qt optimisation options
 fi
 make
Clean: sh
 make distclean || make clean || true

Package: fracplanet
Architecture: any
Depends: []
Suggests: povray,blender
Description: Fractal terrain generator
 Fracplanet generates random planets and terrain with oceans, 
 mountains, icecaps and rivers.  Parameters are specified interactively 
 and the results displayed using OpenGL.  The generated objects can be
 exported for Pov-Ray or Blender.
Install: sh
 yada install -bin fracplanet
 yada install -doc fracplanet.htm fracplanet.css
 yada install -doc BUGS TODO THANKS changelog
 yada install -man man/man1/fracplanet.1
EOF

yada rebuild

# Could do 
#   dpkg-buildpackage -rfakeroot
# now but better to build a source file then build it in pbuilder

cd ..
dpkg-source -b fracplanet-${VER} fracplanet_${VER}.orig.tar.gz

#echo "Updating pbuilder (sudo auth maybe required)"
#sudo pbuilder update

mkdir result
echo "Building package (assumes pbuilder set up as per Cow Book)"
sudo pbuilder build --buildresult ./result fracplanet_${VER}-${REV}.dsc

sudo chown ${USER}:${USER} result/*

echo "Don't forget to lintian and linda"
