#!/bin/bash -e

# Execute this to package up fracplanet as a .tar.gz.
# This is the script used to build the tarballs released on sourceforge

VERSION=`./VERSION`

cd ..

PRUNEDIRS='-name moc -prune -o -name obj -prune -o -name pkg_* -prune'

FILES_MISC=`ls fracplanet/{README,BUILD,LICENSE,TODO,CHANGES,BUGS,VERSION,THANKS,configure,doxygen.cfg,mktgz,testtgz,mkdeb,fracplanet.css,fracplanet.htm,htm_to_qml.xsl}`
FILES_PRO=`find fracplanet ${PRUNEDIRS} -o -name '*.pro' -print`
FILES_MAN=`find fracplanet/man -name '*.1' -print`
FILES_H=`find fracplanet ${PRUNEDIRS} -o -name usage_text.h -prune -o -name '*.h' -print`
FILES_C=`find fracplanet ${PRUNEDIRS} -o -name usage_text.h -prune -o -name '*.c' -print`
FILES_CPP=`find fracplanet ${PRUNEDIRS} -o -name '*.cpp' -print`

FILES="$FILES_MISC $FILES_PRO $FILES_MAN $FILES_H $FILES_C $FILES_CPP"

tar cvfz fracplanet/fracplanet.tar.gz $FILES

echo "***"
echo "*** Suggestion:"
echo "*** mv fracplanet.tar.gz fracplanet-$VERSION.tar.gz"
echo "*** ./testtgz fracplanet-$VERSION.tar.gz"
echo "***"
