#!/bin/bash

# Script to echo the current version number.
# THIS IS THE ONLY PLACE A VERSION NUMBER SHOULD BE SPECIFIED

# NB If you edit this, you will need to "make distclean" and then rebuild (./BUILD) as there is no dependency checking

# Avoid '-' or '_' in the version as it confuses mkdeb.
# Use dev or wip qualifier while working to a release.

echo "0.4.0"
