.TH FRACPLANET 1 "3 Apr 2006" "www.timday.com" "Fracplanet"

.SH NAME
fracplanet \- Create and view random fractal terrain and planets.

.SH SYNOPSIS
fracplanet
[
.I <QtOptions>
]
[
.B --display-list
]
[
.B --help
]
[
.B --wireframe
]

.SH DESCRIPTION

.B Fracplanet 
generates random planets and terrain with oceans, 
mountains, icecaps and rivers.  Parameters are specified interactively 
and the results displayed using OpenGL.  The generated objects can be
exported for Pov-Ray or Blender.

A document fully describing usage via the application's GUI is
accessible from the application's "About" menu once it is running.

.SH OPTIONS

.TP 0.5i
.I <QtOptions>
Standard options recognised by the Qt toolkit (for example
.B \-geometry
.I <width>x<height>
Note that these use the single-dash option style.
).

.TP 0.5i
.B --display-list, -d
Start up the application with rendering in display list mode by default
(c.f immediate mode).
This is particularly useful when the application is running remotely as the
generated meshes are only sent to the local OpenGL display hardware once.

.TP 0.5i
.B --help, -h
Display a list of recognised arguments.

.TP 0.5i
.B --wireframe, -w
Start application with rendering set to wireframe mode.

.SH AUTHOR
.B fracplanet
was written by Tim Day (www.timday.com) and is released
under the conditions of the GNU General Public License.
For further details see the application's "About" dialog
or the file LICENSE supplied with the source code.
