.TH FRACPLANET 1 "3 Apr 2006" "www.timday.com" "Fracplanet"

.SH NAME
fracplanet \- Create and view random fractal terrain and planets.

.SH SYNOPSIS
fracplanet
[
.I <QtOptions>
]

.SH DESCRIPTION

.B Fracplanet 
generates random planets and terrain with oceans, 
mountains, icecaps and rivers.  Parameters are specified interactively 
and the results displayed using OpenGL.  The generated objects can be
exported for Pov-Ray or Blender.

A document fully describing usage via the application's GUI is
accessible from the application's "About" menu once it is running.

.SH OPTIONS

.TP 0.5i
.I <QtOptions>
Standard options recognised by the Qt toolkit (for example
.B \-geometry
.I <width>x<height>
).

.SH AUTHOR
.B fracplanet
was written by Tim Day (www.timday.com) and is released
under the conditions of the GNU General Public License.
For further details see the application's "About" dialog
or the file LICENSE supplied with the source code.
